spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/batchdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  batch:
    job:
      names: ${job.name:NONE}